# Alexis Johnson

- Assignment 2
- BUSA 423
- 7/19/2022

### 1. Write a program for flipping a coin 10,000 times and store the results in a list. After which, identify the number of streaks. (Streak - a series of 5 or more heads or tails) (20) Hint: use random.randint() function to create the coin flip.

In [144]:
import random

flips = []

for i in range(10000):
    flips.append(random.randint(1,2))
    
null = 0
heads = 0
tails = 0
for i in range(len(flips)):
    null = flips[i]
    j = i +1
    count = 0
    while j < len(flips) and flips[i] == flips[j]:
        count += 1
        j += 1
    if count >4:
        if flips[i] == 1:
            heads += 1
        else:
            tails += 1
    i =j
    
print('In ' + str(len(flips)) + ' flips there were ' + str(flips.count(1)) + ' heads with ' + str(flips.count(2)) + ' tails.')
print('Head streaks equal ' + str(heads) + ' and tail streaks equal ' + str(tails))

In 10000 flips there were 4934 heads with 5066 tails.
Head streaks equal 153 and tail streaks equal 156


### 2. Write a program to take user inputs (number of swords, diamonds, gold coins, ropes and potions) for a video game and store them in a dictionary. After which print the following output. (20)
- Inventory:
    - 4 swords
    - 10 diamonds
    - 6 gold coins
    - 3 ropes
    - 2 potions

In [119]:
inventory = {'Swords': 4, 'Diamonds': 10, 'Gold Coins': 6, 'Ropes': 3, 'Potions': 2}

print("Inventory")
for key, value in inventory.items():
    print(str(value) + ' ' + key )

Inventory
4 Swords
10 Diamonds
6 Gold Coins
3 Ropes
2 Potions


### 3. Repeat question 1 using arrays. (20)

In [94]:
import numpy as np
import random

flipsarr = np.random.randint(2,size=(10000))

value=0
heads=0
tails=0

for i in range(len(flipsarr)):
    value = flipsarr[i]
    j = i + 1
    count = 0
    while j < len(flipsarr) and flipsarr[i] == flipsarr[j]:
        count += 1
        j += 1
    if count >4:
        if flipsarr[i] == 0:
            heads += 1
        else:
            tails += 1
    i =j

print('In 10,000 flips there were' +  str(np.count_nonzero(flipsarr)) + 'heads and ' + str(len(flipsarr) - str(np.count_nonzero(flipsarr)) + 'tails.')
print('With ' + str(heads) + ' head streaks and ' + str(tails) + ' tail streaks. Totaling ' + str(tails+heads) + ' streaks.')

SyntaxError: invalid syntax (1123777852.py, line 25)

### 4. Create a game with the following instructions. (40)
- a. There are 3 players and 10 iterations.
- b. In each iteration, every player rolls a die.
- c. The total score for each player is calculated by adding up the 10 rolls.
- d. The player with the highest total score is declared as the winner.
- Hint: use random.randint() function to create the die rolls.

In [137]:
import random
import numpy as np

scores = np.zeros((3,10), dtype=int)

for i in range(10):
    for j in range(3):
        scores[j][i] = random.randint(1,6)
        
print(scores)
player1 = np.sum(scores[0])
player2 = np.sum(scores[1])
player3 = np.sum(scores[2])

print('Player 1s score' + ' ' + str(player1))
print('Player 2s score' + ' ' + str(player2))
print('Player 3s score' + ' ' + str(player3) + "\n")

if player1 > player2 and player1 > player3:
    print('The winner is player 1')
elif player2 > player1 and player2 > player3:
    print('The winner is player 2')
else:
    print('Player 3 is th ewinner.')

[[1 3 5 6 1 2 1 3 4 5]
 [6 3 4 6 1 6 6 5 4 4]
 [2 4 2 3 6 3 5 5 4 6]]
Player 1s score 31
Player 2s score 45
Player 3s score 40

The winner is player 2
