## Practice Questions - Strings & Data Structures

#### Question 1: 

Given an original list consiting of values: 22, 41, 33, 66, 8, 12 and 90. Use **append(), extend(), insert(), and concatenation** to add the values 32, 45, 16 and 11 to the list. 

In [42]:
#concatenation
data = [22,41,33,66,8,12,90]
new_data = [32,45,16,11]
data = data + new_data
print(data)

#append
data = [22,41,33,66,8,12,90]
data.append(32)
data.append(45)
data.append(16)
data.append(11)
print(data)

#extend
data = [22,41,33,66,8,12,90]
data.extend([32,45,16,11])
print(data)

#insert
data = [22,41,33,66,8,12,90]
data.insert(7,32)
data.insert(2,45)
data.insert(4,16)
data.insert(5,11)
print(data)

[22, 41, 33, 66, 8, 12, 90, 32, 45, 16, 11]
[22, 41, 33, 66, 8, 12, 90, 32, 45, 16, 11]
[22, 41, 33, 66, 8, 12, 90, 32, 45, 16, 11]
[22, 41, 45, 33, 16, 11, 66, 8, 12, 90, 32]


#### Question 2: 

Write a Python program that tests whether a list is empty or not. Repeat the task for testing an empty string.

In [50]:
a = []
print('Length of a:', len(a))


str_1 = ''
str_2 = ""
print('Empty?:', end = "")
if (len(str_1)==0):
    print('yes')
else:
    print('no')

Length of a: 0
Empty?:yes


#### Question 3: 

- How many times does "dream" appear in the text?

- Where is this text from? 

- Create a python code to print the text.

Dream on\
Dream on\
I dream on\
Dream a little, I'll dream on\
Dream on\
I dream on\
I dream on

Dream a little, I'll dream on\
Dream on\
Dream on\
Dream on\
I'll dream on\
Dream on\
Dream on\
I dream on

In [110]:
print(" 'Dream' appears 17 times in the text")
print(' This text is a lyric from the song "Dream on by Aerosmith"')

dream_1 = [1,2,5,10,11,12,14,15]
dream_2 = [3,6,7,16]
dream_3 = [4,9]
dream_4 = [4,9,13]

for i in range(1,17):
    if i in dream_1:
        print('Dream on')
    elif i in dream_2:
        print('I dream on')
    elif i in dream_3 and i in dream_4:
        print('Dream a little, Ill dream on')
    elif i in dream_4:
        print('Ill dream on')
    else:
        print('')

 'Dream' appears 17 times in the text
 This text is a lyric from the song "Dream on by Aerosmith"
Dream on
Dream on
I dream on
Dream a little, Ill dream on
Dream on
I dream on
I dream on

Dream a little, Ill dream on
Dream on
Dream on
Dream on
Ill dream on
Dream on
Dream on
I dream on


#### Question 4: 

Create a dictionary, with keys being the name of employees: Oliver, Myers, Noah and Fallon. 

Add the values age (random - between 40 and 60), income (random between 100,000 and 150,000) and rating (random between 3.0 and 5.0) 

In [112]:
import random

database = {'Oliver -':{'age': random.randint(40,60), 'income': random.randint(100000,150000), 'rating':random.uniform(3.0,5.0)}, 'Myers -':{'age': random.randint(40,60), 'income': random.randint(100000,150000), 'rating':random.uniform(3.0,5.0)}, 'Noah -':{'age': random.randint(40,60), 'income': random.randint(100000,150000), 'rating':random.uniform(3.0,5.0)}, 'Fallon -':{'age': random.randint(40,60), 'income': random.randint(100000,150000), 'rating':random.uniform(3.0,5.0)}}

for key, value in database.items():
    print(key + ' ' + str(value))
        


Oliver - {'age': 54, 'income': 130097, 'rating': 3.903572695616468}
Myers - {'age': 41, 'income': 128476, 'rating': 4.983658484590036}
Noah - {'age': 43, 'income': 122045, 'rating': 3.9014179753593727}
Fallon - {'age': 43, 'income': 108712, 'rating': 3.320565019685238}


#### Question 5: 

Create the following student data into 2 sub dictionaries based on the scores. (score <= 10 & score > 10)

In [120]:
students = {"student_1" : 13 , "student_2" : 17 , "student_3" : 9 , "student_4" : 15 , "student_5" : 8 , "student_6" : 14 , 
            "student_7" : 16 , "student_8" : 12 , "student_9" : 13 , "student_10" : 15 , "student_11" : 14 , "student_112" : 9 , 
            "student_13" : 10 , "student_14" : 12 , "student_15" : 13 , "student_16" : 7 , "student_17" : 12 , "student_18" : 15 , 
            "student_19" : 9 , "student_20" : 17 ,}

for key, value in students.items ():
    if (value <10):
        nonAdmittedStudent[key] = value
    else:
        admittedStudents[key] = value

print ("Admitted students:")
print (admittedStudents)
print ("Students not admitted:")
print (nonAdmittedStudent)

Admitted students:
{'student_1': 13, 'student_2': 17, 'student_4': 15, 'student_6': 14, 'student_7': 16, 'student_8': 12, 'student_9': 13, 'student_10': 15, 'student_11': 14, 'student_13': 10, 'student_14': 12, 'student_15': 13, 'student_17': 12, 'student_18': 15, 'student_20': 17}
Students not admitted:
{'student_3': 9, 'student_5': 8, 'student_112': 9, 'student_16': 7, 'student_19': 9}


#### Question 6: 


Write a python program that asks the user to enter an integer n and return a dictionary whose keys are integers 1, 2, 3, ... n and whose values ​​are 1! , 2! , 3! , … , n!

In [116]:
factorial = {}

number = int(input("Enter a number: "))

for I in range(1, number + 1):
 factorial[i] = I * factorial. get(i - 1, 1)


print(factorial)

Enter a number: 25
{16: 25}


#### Question 7: 
    
Write a program to identify the largest word in a string.

In [94]:
def find_longest_word(word_list):
    longest_word = ''
    for word in word_list:
        if len(word) > len(longest_word):
            longest_word = word
    print (longest_word)

words = input('Put your words here')  
word_list = words.split()  
find_longest_word(word_list)  



Put your words hereI have a headache
headache


#### Question 8: 
    
Given an integer array, write a program to identify all the rows with values greater than the mean of the entire data.

In [13]:
def printAboveAvg(arr, a):
 
    avg = 0
    for i in range(a):
        avg = avg + arr[i]
         
    avg = avg // a
    for i in range(a):
        if arr[i] > avg:
            print(arr[i], end = " ")
            
arr = [15, 11, 75, 9, 50]
a = len(arr)
printAboveAvg(arr, a)

75 50 

#### Question 9: 
    
Given an array of strings, write a program to create a new array which contains the lengths of the strings in ascending order

In [142]:
 A = ['lm', 'lmn', 'lmno', 'lmnop']
    
A.sort()
print('sorted list:', A)
B = len(A[0])
C = len(A[1])
D = len(A[2])
E = len(A[3])

K = [B,C,D,E]
print('Lenght of elements in asc order:', K)

sorted list: ['lm', 'lmn', 'lmno', 'lmnop']
Lenght of elements in asc order: [2, 3, 4, 5]


#### Question 10: 
    
Write a program to calculate the sum of the diagonal elements of a **n X n** matrix. 

In [8]:
import numpy as np

arr=np.random.randint(10, size=(3,3))

print('The Matrix is:')
print(arr)

trace=np.trace(arr)

print('Trace of given 3x3 matrix:')
print(trace)

The Matrix is:
[[3 6 6]
 [4 8 6]
 [5 2 3]]
Trace of given 3x3 matrix:
14
